#!/bin/sh

command=$1

echo "prerequisites : "
read prerequisites
echo "verify : "
read verify
echo "mensagem : "
read mensagem
echo "prepare : "
read prepare

mkdir ../../var/desafios/$1
cd ../../var/desafios/$1
echo 
