#!/bin/bash

#input:
#if nothing, mostrar the quests that can be made
#if not nothing, need to be a name and a action
#name is anything
#action = enum {verificar,aceitar,mostrar}



howToUse(){
	echo "Digite uma das duas formas abaixo"
	echo "$0"
	echo "$0 nomeDaQuest [verificar | aceitar | mostrar]"
}

isAccepted(){
	quest=$1
	grep $quest /home/$USER/.desafios/questsAccepted >/dev/null
}

#confParser.awk /etc/desafios.conf | read questPaths

information(){
	orderedQuests=`mktemp`
	aux=`mktemp`
	echo "Aperte 'q' para sair"
	ls /var/games/desafios | sort > $orderedQuests;
	cat /home/$USER/.desafios/questsDone | sort > $aux;
	echo "então, você pode fazer essas quests : ";
	diff $orderedQuests $aux | grep "<" | sed 's/< //g' | xargs -n1 simplify 2>/dev/null| head ;
	rm $PWD/simplify*; #gambiarra por causa de broken pipe error acima.
			   #tão gambiarra que deve ter no kernel do windows
	rm $orderedQuests;
	rm $aux;
	test -s /home/$USER/.desafios/questsAccepted && (echo "e ainda por cima, você esta fazendo essas quests : " ; cat /home/$USER/.desafios/questsAccepted;)
}

if [ $# -eq 0 ]; #if there's no arguments
then
	information | less
elif [ $# -eq 2 ]; 
then
	quest=$1
	action=$2
	questsDone="/home/$USER/.desafios/questsDone"
	isAccepted $quest
	if [ "$action" = "verificar" ] && [ $? -eq 0 ];
	then
		. /var/games/desafios/$quest/verify
		if [ $? -eq 0 ]; #Good Game
		then
			echo $quest >>$questsDone
			aux=`mktemp questsDoneXXXX`
			sort -u $questsDone > $aux
			mv $aux $questsDone
			sed '/$quest/d' -i /home/$USER/.desafios/questsAccepted
			echo "você completou a quest $quest"
		else
			echo "Você não terminou essa quests, gafanhoto"
		fi
	elif [ "$action" = "aceitar" ];
	then
		differences=`diff /var/games/desafios/$quest/prerequisites /home/$USER/.desafios/questsDone | grep "<" | sed 's/< //g'`
		if [ -z "$differences" ];
		then
			"./var/games/desafios/$quest/prepare"
			echo ls >> /home/$USER/.desafios/questsAccepted
			echo "você aceitou a quest nomeada $quest"
		else
			echo "desculpe, você não cumpriu os prerequisitos"
			exit 1
		fi	
	elif [ "$action" = "mostrar" ];
	then
		prerequisites=/var/games/desafios/$quest/prerequisites
		difference=`diff $prerequisites /home/$USER/.desafios/questsDone | grep "<" | sed 's/< //g'`
		if [ -z "$difference" ];
		then
			cat /var/games/desafios/$quest/text
		else
			echo "os prerequisitos que você ainda não tem são : "
			echo $difference
		fi
	fi
else
	howToUse
fi
