#!/bin/sh



quest=$1;

questsDone=`mktemp simplifyXXX`;
prerequisites=`mktemp simplifyXXX`;
differe=`mktemp simplifyXXX`
trap PIPE

cat /home/$USER/.desafios/questsDone | sort > $questsDone;
cat /var/games/desafios/$quest/prerequisites | sort > $prerequisites
diff $prerequisites $questsDone | grep "<" | sed 's/< //g' > $differe;
test -s $differe || echo $quest;
rm $questsDone $prerequisites $differe

